version: '2'
services:
    mistral-app:
        image: mistral
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mistral-mysql:3306/mistral?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mistral-mysql:
        extends:
            file: mysql.yml
            service: mistral-mysql
